[package]
name = "sledlite-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
chrono = "0.4.41"
crc32fast = "1.5.0"
crossbeam-epoch = "0.9.18"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
